#include "include/import.h"

#define BOOST_AFIO_V1_STL11_IMPL std
#define BOOST_AFIO_V1_FILESYSTEM_IMPL boost
#define BOOST_AFIO_V1_ASIO_IMPL asio

#define BOOST_AFIO_V1 (boost), (afio), (BOOST_BINDLIB_NAMESPACE_VERSION(v1, BOOST_AFIO_V1_STL11_IMPL, BOOST_AFIO_V1_FILESYSTEM_IMPL, BOOST_AFIO_V1_ASIO_IMPL), inline)
#define BOOST_AFIO_V1_NAMESPACE       BOOST_BINDLIB_NAMESPACE      (BOOST_AFIO_V1)
#define BOOST_AFIO_V1_NAMESPACE_BEGIN BOOST_BINDLIB_NAMESPACE_BEGIN(BOOST_AFIO_V1)
#define BOOST_AFIO_V1_NAMESPACE_END   BOOST_BINDLIB_NAMESPACE_END  (BOOST_AFIO_V1)
#define BOOST_STL11_ATOMIC_MAP_NAMESPACE_BEGIN        BOOST_BINDLIB_NAMESPACE_BEGIN(BOOST_AFIO_V1, (stl11, inline))
#define BOOST_STL11_ATOMIC_MAP_NAMESPACE_END          BOOST_BINDLIB_NAMESPACE_END  (BOOST_AFIO_V1, (stl11, inline))

BOOST_STL11_ATOMIC_MAP_NAMESPACE_BEGIN

int foo()
{
  return 1;
}

BOOST_STL11_ATOMIC_MAP_NAMESPACE_END

//extern "C" void printf(const char *, ...);
int main(void)
{
  BOOST_AFIO_V1_NAMESPACE::foo();
  //printf("foo=%d\n", BOOST_AFIO_V1_NAMESPACE::foo());
  return 0;
}
