#include "include/import.hpp"

#define BOOST_AFIO_V1_STL11_IMPL std
#define BOOST_AFIO_V1 (boost), (afio), (BOOST_LOCAL_BIND_NAMESPACE_VERSION(v1, BOOST_AFIO_V1_STL11_IMPL), inline)
#define BOOST_AFIO_V1_NAMESPACE       BOOST_LOCAL_BIND_NAMESPACE      (BOOST_AFIO_V1)
#define BOOST_AFIO_V1_NAMESPACE_BEGIN BOOST_LOCAL_BIND_NAMESPACE_BEGIN(BOOST_AFIO_V1)
#define BOOST_AFIO_V1_NAMESPACE_END   BOOST_LOCAL_BIND_NAMESPACE_END  (BOOST_AFIO_V1)
#define BOOST_STL11_ATOMIC_MAP_NAMESPACE_BEGIN        BOOST_LOCAL_BIND_NAMESPACE_BEGIN(BOOST_AFIO_V1, (stl11, inline))
#define BOOST_STL11_ATOMIC_MAP_NAMESPACE_END          BOOST_LOCAL_BIND_NAMESPACE_END  (BOOST_AFIO_V1, (stl11, inline))

BOOST_STL11_ATOMIC_MAP_NAMESPACE_BEGIN

int foo()
{
  return 1;
}

BOOST_STL11_ATOMIC_MAP_NAMESPACE_END

extern "C" void printf(const char *, ...);
int main(void)
{
  printf("foo=%d\n", BOOST_AFIO_V1_NAMESPACE::foo());
  return 0;
}
