/* Thread related functions
(C) 2016 Niall Douglas http://www.nedprod.com/
File Created: Jun 2016


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef BOOSTLITE_UTILS_THREAD_HPP
#define BOOSTLITE_UTILS_THREAD_HPP

#ifdef __linux__
#include <sys/syscall.h>  // for gettid()
#endif

namespace boost_lite
{
  namespace utils
  {
    namespace thread
    {
#ifdef _WIN32
      namespace win32
      {
        extern "C" __declspec(dllimport) unsigned long __stdcall GetCurrentThreadId(void);
      }
#endif
      //! The thread id of the calling thread
      inline unsigned this_thread_id() noexcept
      {
#ifdef _WIN32
        return (unsigned) win32::GetCurrentThreadId();
#elif defined(__linux__)
        return (unsigned) syscall(SYS_gettid);
#else
        return (unsigned) pthread_getthreadid_np();
#endif
      }
    }
  }
}

#endif
