install(EXPORT ${PROJECT_NAME}Exports
  NAMESPACE ${PROJECT_NAME}::
  COMPONENT headers
  DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}"
)
if (TARGET ${PROJECT_NAME}_sl)
  install(EXPORT ${PROJECT_NAME}SlExports
    NAMESPACE ${PROJECT_NAME}::
    COMPONENT sl
    DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}"
  )
  endif()
if (TARGET ${PROJECT_NAME}_dl)
  install(EXPORT ${PROJECT_NAME}DlExports
    NAMESPACE ${PROJECT_NAME}::
    COMPONENT dl
    DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}"
  )
endif()