/* Small PRNG
(C) 2016 Niall Douglas http://www.nedprod.com/
File Created: Sept 2016


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef BOOSTLITE_ALGORITHM_SMALL_PRNG_HPP
#define BOOSTLITE_ALGORITHM_SMALL_PRNG_HPP

#include "../utils/thread.hpp"

#include <cstdint>
#include <iterator>

BOOSTLITE_NAMESPACE_BEGIN

namespace algorithm
{
  namespace small_prng
  {
    /*! \class small_prng
    \brief From http://burtleburtle.net/bob/rand/smallprng.html
    */
    class small_prng
    {
      uint32_t a;
      uint32_t b;
      uint32_t c;
      uint32_t d;

      static inline uint32_t rot(uint32_t x, uint32_t k) noexcept { return (((x) << (k)) | ((x) >> (32 - (k)))); }
    public:
      explicit small_prng(uint32_t seed = 0xdeadbeef) noexcept
      {
        a = 0xf1ea5eed;
        b = c = d = seed;
        for(size_t i = 0; i < 20; ++i)
          (*this)();
      }

      inline uint32_t operator()() noexcept
      {
        uint32_t e = a - rot(b, 27);
        a = b ^ rot(c, 17);
        b = c + d;
        c = d + e;
        d = e + a;
        return d;
      }
    };

    //! \brief A thread safe small prng seeded with the thread id
    inline small_prng &thread_local_prng()
    {
      static thread_local small_prng v(utils::thread::this_thread_id());
      return v;
    }

    template <class RandomIt> void random_shuffle(RandomIt first, RandomIt last, small_prng &r = thread_local_prng())
    {
      typename std::iterator_traits<RandomIt>::difference_type i, n;
      n = last - first;
      for(i = n - 1; i > 0; --i)
      {
        using std::swap;
        swap(first[i], first[r() % (i + 1)]);
      }
    }
  }
}

BOOSTLITE_NAMESPACE_END

#endif
