/* String algorithms
(C) 2016 Niall Douglas http://www.nedprod.com/
File Created: Jun 2016


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef BOOSTLITE_ALGORITHM_SECDEC_ECC_HPP
#define BOOSTLITE_ALGORITHM_SECDEC_ECC_HPP

#include "../config.hpp"

BOOSTLITE_NAMESPACE_BEGIN

namespace algorithm
{
  namespace small_prng
  {
    // From http://burtleburtle.net/bob/rand/smallprng.html
    typedef unsigned int u4;
    typedef struct ranctx
    {
      u4 a;
      u4 b;
      u4 c;
      u4 d;
    } ranctx;

#define rot(x, k) (((x) << (k)) | ((x) >> (32 - (k))))
    static u4 ranval(ranctx *x)
    {
      u4 e = x->a - rot(x->b, 27);
      x->a = x->b ^ rot(x->c, 17);
      x->b = x->c + x->d;
      x->c = x->d + e;
      x->d = e + x->a;
      return x->d;
    }

    static void raninit(ranctx *x, u4 seed)
    {
      u4 i;
      x->a = 0xf1ea5eed, x->b = x->c = x->d = seed;
      for(i = 0; i < 20; ++i)
      {
        (void) ranval(x);
      }
    }
  }
}

BOOSTLITE_NAMESPACE_END

#endif
