/* unit_test.hpp
Provides lightweight Boost.Test macros
(C) 2014 Niall Douglas http://www.nedprod.com/
File Created: Nov 2014


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef BOOST_BINDLIB_BOOST_UNIT_TEST_HPP
#define BOOST_BINDLIB_BOOST_UNIT_TEST_HPP
 
#include "../config.hpp"
#include <atomic>
#include <mutex>
#define CATCH_CONFIG_PREFIX_ALL
#define CATCH_CONFIG_RUNNER
#include "../../CATCH/single_include/catch.hpp"

#ifndef BOOST_CATCH_ELIDE_SUCCESSES
# define BOOST_CATCH_ELIDE_SUCCESSES 0
#endif

namespace boost { namespace unit_test_as_catch {
  static std::mutex &__global_lock()
  {
    static std::mutex lock;
    return lock;
  }
  static std::mutex &global_lock()
  {
    static std::atomic<int> c;
    while(2!=c.load(std::memory_order_acquire))
    {
      int expected=0;
      if(c.compare_exchange_weak(expected, 1, std::memory_order_acquire, std::memory_order_consume))
      {
        __global_lock();
        c.store(2, std::memory_order_release);
        break;
      }
    }
    return __global_lock();
  }
} } // namespace

#define BOOST_CATCH_LOCK(stmt) { std::lock_guard<decltype(::boost::unit_test_as_catch::global_lock())> ___g(::boost::unit_test_as_catch::global_lock()); stmt; }
#define BOOST_CATCH_LOCK_IF(p, stmt) if(!(p) || !BOOST_CATCH_ELIDE_SUCCESSES) { std::lock_guard<decltype(::boost::unit_test_as_catch::global_lock())> ___g(::boost::unit_test_as_catch::global_lock()); stmt; }

#define BOOST_TEST_MESSAGE(msg) BOOST_CATCH_LOCK(CATCH_INFO(msg))
#define BOOST_FAIL(msg) BOOST_CATCH_LOCK(CATCH_FAIL(msg))
#define BOOST_CHECK_MESSAGE(p, msg) BOOST_CATCH_LOCK_IF((p), if(!(p)) CATCH_INFO(msg))
#define BOOST_CHECK(expr) BOOST_CATCH_LOCK_IF((expr), CATCH_CHECK(expr))
#define BOOST_CHECK_THROWS(expr)\
try{\
    expr;\
    BOOST_CATCH_LOCK(CATCH_CHECK_THROWS(;)) \
}catch(...){BOOST_CATCH_LOCK_IF(true, CATCH_CHECK_THROWS(throw))}
#define BOOST_CHECK_NO_THROW(expr)\
try{\
    expr;\
    BOOST_CATCH_LOCK_IF(true, CATCH_CHECK_NOTHROW(;)) \
}catch(...){BOOST_CATCH_LOCK(CATCH_CHECK_NOTHROW(throw))}

#ifdef _MSC_VER
# define BOOST_BINDLIB_ENABLE_MULTIPLE_DEFINITIONS __declspec(selectany)
#elif defined __GNUC__
# define BOOST_BINDLIB_ENABLE_MULTIPLE_DEFINITIONS __attribute__((weak))
#else
# define BOOST_BINDLIB_ENABLE_MULTIPLE_DEFINITIONS inline
#endif

#define BOOST_AUTO_TEST_SUITE(name) \
BOOST_BINDLIB_ENABLE_MULTIPLE_DEFINITIONS int main( int argc, char* const argv[] ) \
{ \
  int result = Catch::Session().run( argc, argv ); \
  return result; \
}
#define BOOST_AUTO_TEST_SUITE_END()
#define BOOST_AUTO_TEST_CASE(test_name, desc) CATCH_TEST_CASE(#test_name, desc)

#endif
