#ifndef BOOSTLITE_CONFIG_HPP
#define BOOSTLITE_CONFIG_HPP

#include "revision.hpp"

#define BOOSTLITE_VERSION_GLUE2(a, b) a##b
#define BOOSTLITE_VERSION_GLUE(a, b) BOOSTLITE_VERSION_GLUE2(a, b)

// clang-format off
#define BOOSTLITE_NAMESPACE boost_lite::BOOSTLITE_VERSION_GLUE(_, BOOSTLITE_PREVIOUS_COMMIT_UNIQUE)
#define BOOSTLITE_NAMESPACE_BEGIN namespace boost_lite { inline namespace BOOSTLITE_VERSION_GLUE(_, BOOSTLITE_PREVIOUS_COMMIT_UNIQUE) {
#define BOOSTLITE_NAMESPACE_END } }
// clang-format on

#ifdef _MSC_VER
#define BOOSTLITE_BIND_MESSAGE_PRAGMA2(x) __pragma(message(x))
#define BOOSTLITE_BIND_MESSAGE_PRAGMA(x) BOOSTLITE_BIND_MESSAGE_PRAGMA2(x)
#define BOOSTLITE_BIND_MESSAGE_PREFIX(type) __FILE__ "(" BOOSTLITE_BIND_STRINGIZE2(__LINE__) "): " type ": "
#define BOOSTLITE_BIND_MESSAGE_(type, prefix, msg) BOOSTLITE_BIND_MESSAGE_PRAGMA(prefix msg)
#else
#define BOOSTLITE_BIND_MESSAGE_PRAGMA2(x) _Pragma(#x)
#define BOOSTLITE_BIND_MESSAGE_PRAGMA(type, x) BOOSTLITE_BIND_MESSAGE_PRAGMA2(type x)
#define BOOSTLITE_BIND_MESSAGE_(type, prefix, msg) BOOSTLITE_BIND_MESSAGE_PRAGMA(type, msg)
#endif
//! Have the compiler output a message
#define BOOSTLITE_MESSAGE(msg) BOOSTLITE_BIND_MESSAGE_(message, BOOSTLITE_BIND_MESSAGE_PREFIX("message"), msg)
//! Have the compiler output a note
#define BOOSTLITE_NOTE(msg) BOOSTLITE_BIND_MESSAGE_(message, BOOSTLITE_BIND_MESSAGE_PREFIX("note"), msg)
//! Have the compiler output a warning
#define BOOSTLITE_WARNING(msg) BOOSTLITE_BIND_MESSAGE_(GCC warning, BOOSTLITE_BIND_MESSAGE_PREFIX("warning"), msg)
//! Have the compiler output an error
#define BOOSTLITE_ERROR(msg) BOOSTLITE_BIND_MESSAGE_(GCC error, BOOSTLITE_BIND_MESSAGE_PREFIX("error"), msg)


#ifdef BOOSTLITE_ENABLE_VALGRIND
#include "../valgrind/drd.h"
#define BOOSTLITE_ANNOTATE_RWLOCK_CREATE(p) ANNOTATE_RWLOCK_CREATE(p)
#define BOOSTLITE_ANNOTATE_RWLOCK_DESTROY(p) ANNOTATE_RWLOCK_DESTROY(p)
#define BOOSTLITE_ANNOTATE_RWLOCK_ACQUIRED(p, s) ANNOTATE_RWLOCK_ACQUIRED(p, s)
#define BOOSTLITE_ANNOTATE_RWLOCK_RELEASED(p, s) ANNOTATE_RWLOCK_RELEASED(p, s)
#define BOOSTLITE_ANNOTATE_IGNORE_READS_BEGIN() ANNOTATE_IGNORE_READS_BEGIN()
#define BOOSTLITE_ANNOTATE_IGNORE_READS_END() ANNOTATE_IGNORE_READS_END()
#define BOOSTLITE_ANNOTATE_IGNORE_WRITES_BEGIN() ANNOTATE_IGNORE_WRITES_BEGIN()
#define BOOSTLITE_ANNOTATE_IGNORE_WRITES_END() ANNOTATE_IGNORE_WRITES_END()
#define BOOSTLITE_DRD_IGNORE_VAR(x) DRD_IGNORE_VAR(x)
#define BOOSTLITE_DRD_STOP_IGNORING_VAR(x) DRD_STOP_IGNORING_VAR(x)
#define BOOSTLITE_RUNNING_ON_VALGRIND RUNNING_ON_VALGRIND
#else
#define BOOSTLITE_ANNOTATE_RWLOCK_CREATE(p)
#define BOOSTLITE_ANNOTATE_RWLOCK_DESTROY(p)
#define BOOSTLITE_ANNOTATE_RWLOCK_ACQUIRED(p, s)
#define BOOSTLITE_ANNOTATE_RWLOCK_RELEASED(p, s)
#define BOOSTLITE_ANNOTATE_IGNORE_READS_BEGIN()
#define BOOSTLITE_ANNOTATE_IGNORE_READS_END()
#define BOOSTLITE_ANNOTATE_IGNORE_WRITES_BEGIN()
#define BOOSTLITE_ANNOTATE_IGNORE_WRITES_END()
#define BOOSTLITE_DRD_IGNORE_VAR(x)
#define BOOSTLITE_DRD_STOP_IGNORING_VAR(x)
#define BOOSTLITE_RUNNING_ON_VALGRIND (0)
#endif

#ifndef BOOSTLITE_IN_THREAD_SANITIZER
#if defined(__has_feature)
#if __has_feature(thread_sanitizer)
#define BOOSTLITE_IN_THREAD_SANITIZER 1
#endif
#elif defined(__SANITIZE_ADDRESS__)
#define BOOSTLITE_IN_THREAD_SANITIZER 1
#endif
#endif
#ifndef BOOSTLITE_IN_THREAD_SANITIZER
#define BOOSTLITE_IN_THREAD_SANITIZER 0
#endif

#ifndef BOOSTLITE_THREAD_LOCAL
#ifdef __cpp_thread_local
#define BOOSTLITE_THREAD_LOCAL thread_local
#elif defined(_MSC_VER)
#define BOOSTLITE_THREAD_LOCAL __declspec(thread)
#elif defined(__GNUC__)
#define BOOSTLITE_THREAD_LOCAL __thread
#else
#error Unknown compiler, cannot set BOOSTLITE_THREAD_LOCAL
#endif
#endif

#endif
