/* has_feature.h
Provides __has_feature for all C++ compilers
(C) 2014 Niall Douglas http://www.nedprod.com/
File Created: Nov 2014


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef BOOST_BINDLIB_HAS_FEATURE_H
#define BOOST_BINDLIB_HAS_FEATURE_H

// Recent GCCs and clangs already do this, so only care about MSVC
// VS2010: _MSC_VER=1600
// VS2012: _MSC_VER=1700
// VS2013: _MSC_VER=1800
// VS2015: _MSC_VER=1900
#ifdef _MSC_VER

#if !defined(__cpp_exceptions) && defined(_CPPUNWIND)
# define __cpp_exceptions 190000
#endif

#if !defined(__cpp_rtti) && defined(_CPPRTTI)
# define __cpp_rtti 190000
#endif


// C++ 11
#if !defined(__cpp_access_control_sfinae)
# define __cpp_access_control_sfinae 190000
#endif

#if !defined(__cpp_alias_templates) && _MSC_VER >= 1800
# define __cpp_alias_templates 190000
#endif

#if !defined(__cpp_alignas) && _MSC_VER >= 1900
# define __cpp_alignas 190000
#endif

#if !defined(__cpp_attributes)
# define __cpp_attributes 190000
#endif

#if !defined(__cpp_constexpr)
# define __cpp_constexpr 190000
#endif

#if !defined(__cpp_decltype) && _MSC_VER >= 1600
# define __cpp_decltype 190000
#endif

#if !defined(__cpp_default_function_template_args) && _MSC_VER >= 1800
# define __cpp_default_function_template_args 190000
#endif

#if !defined(__cpp_defaulted_functions) && _MSC_VER >= 1800
# define __cpp_defaulted_functions 190000
#endif

#if !defined(__cpp_delegating_constructors) && _MSC_VER >= 1800
# define __cpp_delegating_constructors 190000
#endif

#if !defined(__cpp_deleted_functions) && _MSC_VER >= 1800
# define __cpp_deleted_functions 190000
#endif

#if !defined(__cpp_explicit_conversions) && _MSC_VER >= 1800
# define __cpp_explicit_conversions 190000
#endif

#if !defined(__cpp_generalized_initializers) && _MSC_VER >= 1800
# define __cpp_generalized_initializers 190000
#endif

#if !defined(__cpp_implicit_moves) && _MSC_VER >= 1900
# define __cpp_implicit_moves 190000
#endif

#if !defined(__cpp_inheriting_constructors) && _MSC_VER >= 1900
# define __cpp_inheriting_constructors 190000
#endif

#if !defined(__cpp_inline_namespaces) && _MSC_VER >= 1900
# define __cpp_inline_namespaces 190000
#endif

#if !defined(__cpp_lambdas) && _MSC_VER >= 1600
# define __cpp_lambdas 190000
#endif

#if !defined(__cpp_local_type_template_args) && _MSC_VER >= 1600
# define __cpp_local_type_template_args 190000
#endif

#if !defined(__cpp_noexcept) && _MSC_VER >= 1900
# define __cpp_noexcept 190000
#endif

#if !defined(__cpp_nonstatic_member_init) && _MSC_VER >= 1800
# define __cpp_nonstatic_member_init 190000
#endif

#if !defined(__cpp_nullptr) && _MSC_VER >= 1600
# define __cpp_nullptr 190000
#endif

#if !defined(__cpp_override_control) && _MSC_VER >= 1700
# define __cpp_override_control 190000
#endif

#if !defined(__cpp_reference_qualified_functions) && _MSC_VER >= 1900
# define __cpp_reference_qualified_functions 190000
#endif

#if !defined(__cpp_range_for) && _MSC_VER >= 1700
# define __cpp_range_for 190000
#endif

#if !defined(__cpp_raw_string_literals) && _MSC_VER >= 1800
# define __cpp_raw_string_literals 190000
#endif

#if !defined(__cpp_rvalue_references) && _MSC_VER >= 1600
# define __cpp_rvalue_references 190000
#endif

#if !defined(__cpp_static_assert) && _MSC_VER >= 1600
# define __cpp_static_assert 190000
#endif

#if !defined(__cpp_thread_local) && _MSC_VER >= 1900
# define __cpp_thread_local 190000
#endif

#if !defined(__cpp_auto_type) && _MSC_VER >= 1600
# define __cpp_auto_type 190000
#endif

#if !defined(__cpp_strong_enums) && _MSC_VER >= 1700
# define __cpp_strong_enums 190000
#endif

#if !defined(__cpp_trailing_return) && _MSC_VER >= 1600
# define __cpp_trailing_return 190000
#endif

#if !defined(__cpp_unicode_literals)
# define __cpp_unicode_literals 190000
#endif

#if !defined(__cpp_unrestricted_unions) && _MSC_VER >= 1900
# define __cpp_unrestricted_unions 190000
#endif

#if !defined(__cpp_user_literals) && _MSC_VER >= 1900
# define __cpp_user_literals 190000
#endif

#if !defined(__cpp_variadic_templates) && _MSC_VER >= 1800
# define __cpp_variadic_templates 190000
#endif


// C++ 14
#if !defined(__cpp_binary_literals) && _MSC_VER >= 1900
# define __cpp_binary_literals 190000
#endif

#if !defined(__cpp_contextual_conversions) && _MSC_VER >= 1800
# define __cpp_contextual_conversions 190000
#endif

#if !defined(__cpp_decltype_auto) && _MSC_VER >= 1900
# define __cpp_decltype_auto 190000
#endif

#if !defined(__cpp_aggregate_nsdmi) && _MSC_VER >= 1800
# define __cpp_aggregate_nsdmi 190000
#endif

#if !defined(__cpp_digit_separators)
# define __cpp_digit_separators 190000 && _MSC_VER >= 1900
#endif

#if !defined(__cpp_init_captures)
# define __cpp_init_captures 190000 && _MSC_VER >= 1900
#endif

#if !defined(__cpp_generic_lambdas) && _MSC_VER >= 1900
# define __cpp_generic_lambdas 190000
#endif

#if !defined(__cpp_relaxed_constexpr)
# define __cpp_relaxed_constexpr 190000
#endif

#if !defined(__cpp_return_type_deduction) && _MSC_VER >= 1900
# define __cpp_return_type_deduction 190000
#endif

#if !defined(__cpp_runtime_array)
# define __cpp_runtime_array 190000
#endif

#if !defined(__cpp_variable_templates)
# define __cpp_variable_templates 190000
#endif

#endif // _MSC_VER

#endif
