# DO NOT EDIT, GENERATED BY SCRIPT
set(quickcpplib_TESTS
  "test/timing.h"
  "test/test_guard.hpp"
  "test/test_guard2.hpp"
  "test/open_hash_index.cpp"
  "test/packed_backtrace.cpp"
  "test/ringbuffer_log.cpp"
  "test/spinlock_tribool.cpp"
  "test/type_traits.cpp"
)
# DO NOT EDIT, GENERATED BY SCRIPT
set(quickcpplib_COMPILE_TESTS
)
# DO NOT EDIT, GENERATED BY SCRIPT
set(quickcpplib_COMPILE_FAIL_TESTS
)
