# DO NOT EDIT, GENERATED BY SCRIPT
set(quickcpplib_TESTS
  "test/timing.h"
  "test/uint128testdata1.h"
  "test/uint128testdata2.h"
  "test/test_guard.hpp"
  "test/test_guard2.hpp"
  "test/offset_ptr.cpp"
  "test/open_hash_index.cpp"
  "test/packed_backtrace.cpp"
  "test/persistent.cpp"
  "test/ringbuffer_log.cpp"
  "test/secded.cpp"
  "test/signal_guard.cpp"
  "test/spinlock_tribool.cpp"
  "test/type_traits.cpp"
  "test/uint128.cpp"
)
# DO NOT EDIT, GENERATED BY SCRIPT
set(quickcpplib_COMPILE_TESTS
)
# DO NOT EDIT, GENERATED BY SCRIPT
set(quickcpplib_COMPILE_FAIL_TESTS
)
