# DO NOT EDIT, GENERATED BY SCRIPT
set(quickcpplib_TESTS
  "test/async_signal_safe_thread_local.cpp"
  "test/bitwise_trie.cpp"
  "test/casts.cpp"
  "test/function_ptr.cpp"
  "test/hash.cpp"
  "test/issue0040.cpp"
  "test/mem_flush_loads_stores.cpp"
  "test/offset_ptr.cpp"
  "test/open_hash_index.cpp"
  "test/packed_backtrace.cpp"
  "test/ringbuffer_log.cpp"
  "test/secded.cpp"
  "test/signal_guard.cpp"
  "test/spinlock_tribool.cpp"
  "test/start_lifetime_as.cpp"
  "test/test_guard.hpp"
  "test/test_guard2.hpp"
  "test/timing.h"
  "test/type_traits.cpp"
  "test/uint128.cpp"
  "test/uint128testdata1.h"
  "test/uint128testdata2.h"
)
# DO NOT EDIT, GENERATED BY SCRIPT
set(quickcpplib_COMPILE_TESTS
)
# DO NOT EDIT, GENERATED BY SCRIPT
set(quickcpplib_COMPILE_FAIL_TESTS
)
